services:
  strm:
    container_name: strm
    image: ghcr.io/wlnxing/strmgen:${STRM_IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      STRM_ADMIN_USERNAME: admin
      STRM_ADMIN_PASSWORD: admin
      STRM_DB_PATH: /data/strm.db
      STRM_CRON_TZ: Asia/Shanghai
    volumes:
      - ./data/strm:/data:Z
      - ./media:/media:Z
    restart: unless-stopped

  openlist:
    container_name: strm-openlist
    image: docker.io/openlistteam/openlist:latest
    user: "0:0"
    ports:
      - "5244:5244"
    environment:
      TZ: Asia/Shanghai
      UMASK: "022"
      OPENLIST_ADMIN_PASSWORD: admin
    volumes:
      - ./data/openlist:/opt/openlist/data:Z
      - ./media:/media:z
    restart: unless-stopped
